### PR TITLE
[hotfix] Fix incorrect echo in python_ci.yml

### PR DESCRIPTION
**Pull request by GOODBOY008**
Fix incorrect echo in python_ci.yml

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@MartijnVisser PTAL,Thank you~

**Comment by GOODBOY008** [comment]
@snuyanzin Can you review this pr, if you are available. Thank you.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
Removing it isn't the right fix (see the other CI example)

**Comment by GOODBOY008** [comment]
Get it should print jdk variable.

**Review by MartijnVisser — APPROVED** [review]

**Pull request merged**
